# Generated by Django 4.2.17 on 2024-12-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ratingPost',
            field=models.SmallIntegerField(default=0),
        ),
    ]
